# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/country/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/free"
  to = "/index.html"
  status = 200